### PR TITLE
Fixed segmentation fault in depth_image_octomap_updater

### PR DESCRIPTION
**Pull request by CihatAltiparmak**
### Description

The relavant issue:  https://github.com/moveit/moveit2/issues/2964

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — CHANGES_REQUESTED** [review]
Please always explain your changes! 
This looks like a great data type mess: the data array of type `uint8` should store floats (`TYPE_32FC1`), but is passed as a `double` pointer to `getModelDepth()`, which might be the root cause of the segfault.
Now, you allocate an additional `float` array (which takes extra time and memory), still pass it as a `double` pointer (messing up the data) and finally copy the float data as unsigned short into the uint8 slots using some weird transformation. As the `uint8` array is to be interpreted as a float array, this is definitely still wrong.

**Comment by CihatAltiparmak** [comment]
> Now, you allocate an additional `float` array (which takes extra time and memory), still pass it as a `double` pointer (messing up the data) and finally copy the float data as unsigned short into the uint8 slots using some weird transformation.

It actually comes from https://github.com/moveit/moveit2/blob/aece55c3ebe4a88bb9c09b85fa12479b94690c0b/moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp#L468-L492

> Have a look at the [MoveIt1 implementation of that snippet](https://github.com/moveit/moveit/blob/61afd978498291e5113115766d2505c1172bf651/moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp#L410-L411), which seems to use the correct types.

Hmm, thanks, i will give a try converting `getModelDepth(double)` to `getModelDepth(float)`.

**Comment by rhaschke** [comment]
The referenced code looks wrong as well.

**Comment by CihatAltiparmak** [comment]
@rhaschke Should we remove this parts too, what do you think @rhaschke ?

https://github.com/moveit/moveit2/blob/aece55c3ebe4a88bb9c09b85fa12479b94690c0b/moveit_ros/perception/depth_image_octomap_updater/src/depth_image_octomap_updater.cpp#L486-L490

**Review by rhaschke — APPROVED** [review]
This looks better now. Now idea, why #2343 blindly converted all float args to double.

**Comment by rhaschke** [comment]
> Should we remove this parts too (Moveit1 has same implementation)?

No. This code explicitly returns an unsigned short array, i.e. converting float meters into int millimeters.

**Comment by sjahr** [comment]
> This looks better now. Now idea, why #2343 blindly converted all float args to double.

Thanks for referencing moveit1. The reason for the conversation is: https://github.com/cpp-best-practices/cppbestpractices/blob/master/08-Considering_Performance.md#prefer-double-to-float-but-test-first but apparently we ignore the `test_first` part :man_facepalming:

**Comment by CihatAltiparmak** [comment]
I have surfed through the PR you mentioned and i also discovered that the evil is also here ( https://github.com/moveit/moveit2/pull/1578 ) I can be necessary to revert some float-to-double conversions

**Pull request merged**
