### PR TITLE
Remove moveit2_humble.repos and moveit2_iron.repos files

### PR DESCRIPTION
**Pull request by sea-bass**
### Description

The only dependency that was in these files was an old version of `generate_parameter_library` which we do not need to be on at the moment.

I still kept the logic in the Dockerfiles in case there ever needs to be distro-specific repos files in future.

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]

**Review by sjahr — APPROVED** [review]
Thanks!

**Comment by sea-bass** [comment]
Hmm... is the new version of generate_parameter_library actually breaking things on Humble?
https://discourse.ros.org/t/new-packages-for-humble-hawksbill-2024-11-04/40422

https://github.com/moveit/moveit2/actions/runs/11779440054/job/32807896145?pr=3080#step:11:365

**Comment by pac48** [comment]
@sea-bass Which version of generate_parameter_library is being installed by the CI / humble-ci job? I don't see it in the logs.

**Comment by sea-bass** [comment]
> @sea-bass Which version of generate_parameter_library is being installed by the CI / humble-ci job? I don't see it in the logs.

My going theory is that the docker image this is running on is stale because other jobs are failing. I am trying to see if landing #3082 first and then letting the humble moveit image build will fix things.

**Comment by sea-bass** [comment]
It may also be that even though there was a Humble sync last week, the images are not updated?

https://hub.docker.com/_/ros/tags?name=humble

**Comment by sea-bass** [comment]
> > @sea-bass Which version of generate_parameter_library is being installed by the CI / humble-ci job? I don't see it in the logs.
> 
> My going theory is that the docker image this is running on is stale because other jobs are failing. I am trying to see if landing #3082 first and then letting the humble moveit image build will fix things.

Confirming this:

```
$ docker run -it moveit/moveit2:humble-ci bash
root@4c149e72d515:~/ws_moveit# apt list --installed | grep generate-parameter

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ros-humble-generate-parameter-library-py/now 0.3.8-1jammy.20240311.112120 amd64 [installed,local]
ros-humble-generate-parameter-library/now 0.3.8-1jammy.20240311.112627 amd64 [installed,local]
```

If I simply run an `apt install --upgrade` on those packages, I get `0.3.9-1` instead, which has the fixes we need.

Also, these logs from #3082 install the newer version:

https://github.com/moveit/moveit2/actions/runs/11782484963/job/32817611887?pr=3082#step:5:922

So I'm hopeful this will pass once #3082 is in

**Comment by sea-bass** [comment]
This is not passing. Somehow the Humble CI job still is not installing the latest generate_parameter_library. Can't really tell why as I'm not well versed in what industrial_ci is actually doing.

**Comment by sea-bass** [comment]
Humble Docker images are finally being pushed again! This is ready.

**Review by pac48 — APPROVED** [review]

**Pull request merged**
