### PR TITLE
CI: Silent lcov errors

### LINKED ISSUE #3110: SonarScan pipelines are failing on main
### Description

See e.g. https://github.com/moveit/moveit2/actions/runs/11868931947/job/33078707644

I'd be happy to raise a fix (green jobs make me happy), but I'm not too familiar with SonarScan, so some guidance on whether `--ignore-errors mismatch` is the fix, or whether this requires deeper investigation would be appreciated!

### ROS Distro

Humble

### OS and version

SonarScan CI workflow

### Source or binary build?

Source

### If binary, which release version?

_No response_

### If source, which branch?

rolling

### Which RMW are you using?

None

### Steps to Reproduce

Run a SonarScan job

### Expected behavior

Presumably these should not fail

### Actual behavior

They do

### Backtrace or Console output

```
Capture coverage info
  geninfo: WARNING: /usr/include/c++/13/bits/basic_string.h:181: unexecuted block on non-branch line with non-zero hit count.  Use "geninfo --rc geninfo_unexecuted_blocks=1 to set count to zero.
  geninfo: ERROR: mismatched end line for _ZN56RobotTrajectoryTestFixture_ModifyFirstWaypointByPtr_Test8TestBodyEv at /home/runner/work/moveit2/moveit2/.work/target_ws/src/moveit2/moveit_core/robot_trajectory/test/test_robot_trajectory.cpp:361: 361 -> 366
  	(use "geninfo --ignore-errors mismatch ..." to bypass this error)
  Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by rhaschke**
Attempt to fix #3110 and #2866.

### CODE REVIEW

**Comment by rhaschke** [comment]
lcov errors are gone: https://github.com/moveit/moveit2/actions/runs/11897940917/job/33153316613
However, SonarScan execution still fails. I don't even know, what SonarScan actually does. @henningkayser, please decide to fix or disable it.

**Comment by sea-bass** [comment]
SonarScan ingests coverage data, plus runs its own static analysis on the code. It requires re-enabling the paid service, which far as I know has not been enabled since the transition from `ros-planning` to `moveit` orgs.

I would support disabling it for now, and having someone enabling it back if they decide to keep paying for the service.

**Comment by EzraBrooks** [comment]
@sea-bass SonarCloud is still set up. It's free for open-source projects and has not ever been a paid plan for moveit2

**Comment by EzraBrooks** [comment]
That's probably sensical. I also am not sure if renaming the org from ros-planning to moveit might have broken the old API key. I don't appear to be an admin on the MoveIt account on SonarCloud, @henningkayser might need to flip some switches to synchronize maintainer status with GitHub so others of us can do things to it?

**Review by sea-bass — APPROVED** [review]
Thank you @rhaschke! I've updated the required actions based on these changes.

**Comment by rhaschke** [comment]
> I've updated the required actions based on these changes.

What exactly do you mean by this? Which actions did need which (other) changes?

**Comment by sea-bass** [comment]
> > I've updated the required actions based on these changes.
> 
> What exactly do you mean by this? Which actions did need which (other) changes?

Oh, just that adding ccov renamed the rolling-ci job to rolling-ci-ccov, so had to make it required

**Comment by sea-bass** [comment]
Well, this is annoying. It kicks you off the merge queue when Sonar fails. I will merge this and address the issue after.

**Comment by EzraBrooks** [comment]
Thanks for the great work fixing CI! I was meaning to do this myself but it clearly never happened. I've just approved the request to get Codecov fully installed into the moveit org @rhaschke.

side note, the SonarCloud config needs some work from me or @nbbrooks given lessons learned from some other projects.. it's not quite as helpful as it could be since we haven't been iterating on it since it's been broken.

**Comment by nbbrooks** [comment]
Awesome work @rhaschke and @sea-bass !

I was able to fix sonarcloud's initial confusion of the GH org migration when I was poking at #3068 - the dashboard is here https://sonarcloud.io/organizations/moveit (I did not need to make a new key).

**Comment by rhaschke** [comment]
> I've just approved the request to get Codecov fully installed into the moveit org @rhaschke.

Unfortunately, codecov is still not correctly configured for the moveit repo:
image

Do you mind adding me as a moveit org admin?

**Comment by nbbrooks** [comment]
I will look into the admin assignment separately, but moveit2's ccov was deactivated for some reason, I activated it.

**Comment by nbbrooks** [comment]
@rhaschke where are you seeing that? It looks like your upload failed, but succeeded for a separate job a few hours ago 

https://app.codecov.io/github/moveit/moveit2/pulls

**Comment by rhaschke** [comment]
@nbbrooks: I'm asking for MoveIt1:
https://github.com/moveit/moveit/actions/runs/11910451831/job/33208735806#step:12:3553

**Comment by rhaschke** [comment]
Looks like ccov is installed now. However, it states that I should use an upload token.
Didn't you disable the upload tokens in ccov settings?

**Comment by nbbrooks** [comment]
The org setting in codecov was "Required" - I have changed it to "Not required" to solve one thing at a time.

Once we have tings up and running we can decide if we want to add some upload protection by sticking it into a GitHub org secret for the `codecov/codecov-action` action to use.

**Comment by rhaschke** [comment]
Thanks. Now it worked.

**Pull request merged**
