### PR TITLE
Enable iron build jobs in CI

### PR DESCRIPTION
**Pull request by henningkayser**
I thought we had done this already for main, but obviously this was not the case. Iron should also be enforced for PRs.

### CODE REVIEW

**Review by sea-bass — APPROVED** [review]

**Comment by henningkayser** [comment]
> Seems like the [failing test](https://github.com/ros-planning/moveit2/blob/main/moveit_setup_assistant/moveit_setup_srdf_plugins/test/test_srdf.cpp) is doing `rclcpp::init()` and creating an `rclcpp::Logger` instance even though neither is being used.
> 
> This can be removed for this test, but there likely will be more instances like these.

My take is that we might want to rerun this on a fresh set of iron images.

**Comment by sea-bass** [comment]
Sounds good. And actually, that failing test does use `rclcpp` under the hood in an included test fixture, it just wasn't immediately visible from only looking at the file.

**Comment by sea-bass** [comment]
@henningkayser I saw this sitting around and updated / re-ran CI under the assumption that it should work now.

One question though: I notice that with this PR both humble and iron also add a `-testing` image, but the Jazzy CI does not. Should this also add that?

**Comment by sea-bass** [comment]
Iron's about to go EOL, so it's probably not worth putting this in at this point.

**Pull request closed without merging**
