### PR TITLE
Add vel and acc scaling to computeCartesianPath in Humble

### PR DESCRIPTION
**Pull request by liamcarlos**
Hi there,

I updated to Iron to get this capability but noticed Iron's EOL is Friday, so I thought I'd suggest this change for Humble since it has another couple years to EOL

### Description

Please explain the changes you made, including a reference to the related issue if applicable

### Checklist
- [ ] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/moveit/moveit2/blob/main/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://moveit.picknik.ai/humble/doc/examples/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/moveit/moveit2/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
I don't think, computeCartesianPath handles timing at all. It just computes path waypoints. Hence, forwarding the scaling factors does not change anything.
Did you observe any change?

**Comment by mikeferguson** [comment]
This appears to be a back port of #1968? But maybe is missing a line from that PR? And also depends on changes to moveit_msgs that haven't been back ported to humble either AFAICT?

**Comment by liamcarlos** [comment]
@rhaschke It does, I tested it with a UR10e in Iron.  Those lines just seem to be missing from the Humble branch..  Also should  I switch base back to humble branch?  The bot threw me off..

**Comment by rhaschke** [comment]
As pointed out in https://github.com/moveit/moveit2/pull/3048#issuecomment-2447225466, your PR is missing [another line](https://github.com/moveit/moveit2/pull/1968/files#diff-8280560538da5816d20ad3d7c7403fd330fff8620ad65fcaf12cb145c78f2f22L184) from #1968. Moreover, the corresponding message fields are missing. Probably, those API changes are the reason, why this PR wasn't backported to Humble.

**Comment by liamcarlos** [comment]
@rhaschke Yes I noticed that, I'm making that change right now!  Thanks @mikeferguson !

Also found the srv file(GetCartesianPath.srv) that is missing those request fields.  It's missing some other fields i.e. cartesian_speed_limited_link and max_cartesian_speed, but I don't know where those are being used..  I really just want to add velocity and acceleration control to the Humble branch since it will having longer support.

**Pull request closed without merging**
