### PR TITLE
2.11.0

### PR DESCRIPTION
**Pull request by rhaschke**
Release 2.11.0

### CODE REVIEW

**Comment by rhaschke** [comment]
I hope I can directly push the release tag if this one is fast-forwarded...

**Review by sjahr — APPROVED** [review]

**Comment by sjahr** [comment]
@rhaschke I merged this one. The CI failures where not related to the PR. Does this unblock you or do you need additional permissions for the release?

**Comment by rhaschke** [comment]
Thanks for merging. I was able to push the release tag.
Before releasing MoveIt, I have to release `moveit_msgs`.

**Comment by rhaschke** [comment]
Rolling release: https://github.com/ros/rosdistro/pull/42889

**Pull request merged**
