### PR TITLE
Use the non-deprecated service fields for switching controllers

### PR DESCRIPTION
**Pull request by saikishor**
### Description

Hello!

This PR aims to start using the non-deprecated fields of the ros2_control service to switch the controllers. If the changes look good, can this be merged and tagged as well?. It's just there is no release of MoveIt2 in Humble since September 2023. Thank you

### CODE REVIEW

**Comment by sjahr** [comment]
Is that deprecation specific to humble? If not, please target main and we backport this PR automatically

**Review by sjahr — APPROVED** [review]
I see, thanks!

**Comment by saikishor** [comment]
Once this is merged! Can you consider releasing it as well?

**Comment by saikishor** [comment]
hello @sjahr !

Is there any plan to tag and release Humble branch soon?

**Pull request merged**
